# Generated by Django 5.2.10 on 2026-02-04 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_company_name_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('jobId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('showName', models.CharField(max_length=255)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('modifiedOn', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_created_jobs', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, limit_choices_to={'is_customer': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
