# Generated by Django 5.2.10 on 2026-02-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_is_deleted_jobdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='jobId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
