# Generated by Django 5.2.10 on 2026-02-04 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_jobdetails_jobid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='createdBy',
            field=models.ForeignKey(limit_choices_to={'is_superuser': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_created_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
