# Generated by Django 5.2.10 on 2026-02-04 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_jobdetails_createdby'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobdetails',
            options={'verbose_name': 'Job Detail', 'verbose_name_plural': 'Job Details'},
        ),
    ]
