# Generated by Django 5.2.10 on 2026-02-04 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_jobdetails_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='jobId',
        ),
    ]
