# Generated by Django 5.2.10 on 2026-02-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='jobNo',
            field=models.CharField(default='100', max_length=100),
        ),
    ]
