# Generated by Django 5.2.10 on 2026-02-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_jobdetails_jobno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='showName',
            field=models.CharField(max_length=255, unique=True, verbose_name='Show Name'),
        ),
    ]
