# Generated by Django 5.2.10 on 2026-02-12 19:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0011_alter_jobdetails_showname'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TailDownOrder',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cableFinishes', models.CharField(max_length=10, verbose_name='Cable Finishes')),
                ('cableSize', models.CharField(max_length=10, verbose_name='Cable Size')),
                ('topType', models.CharField(max_length=10, verbose_name='Top Type')),
                ('endType', models.CharField(max_length=10, verbose_name='End Type')),
                ('turnbuckle', models.BooleanField(default=False, verbose_name='Turnbuckle')),
                ('chain', models.BooleanField(default=False, verbose_name='Chain')),
                ('tcOrder', models.CharField(max_length=10, verbose_name='Turnbuckle & Chain Order')),
                ('turnbuckleSize', models.CharField(max_length=10, verbose_name='Turnbuckle &Size')),
                ('status', models.CharField(default='Draft', max_length=20, verbose_name='Order Status')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('showName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.jobdetails', to_field='showName', verbose_name='ShowName')),
            ],
        ),
    ]
