# Generated by Django 5.2.10 on 2026-02-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taildownorder',
            name='cableFinishes',
            field=models.CharField(choices=[('gal', 'Galvanized'), ('BLK', 'Blackened')], max_length=10, verbose_name='Cable Finishes'),
        ),
    ]
