# Generated by Django 5.2.10 on 2026-02-17 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_jobdetails_showname'),
        ('customer', '0002_alter_taildownorder_cablefinishes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taildownorder',
            name='showName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.jobdetails', verbose_name='ShowName'),
        ),
    ]
