# Generated by Django 5.2.10 on 2026-02-20 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_taildownorder_showname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taildownorder',
            old_name='order_id',
            new_name='orderId',
        ),
        migrations.AddField(
            model_name='taildownorder',
            name='Name',
            field=models.CharField(default='TailDown No 1', max_length=255),
        ),
        migrations.AddField(
            model_name='taildownorder',
            name='quntity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AlterField(
            model_name='taildownorder',
            name='cableFinishes',
            field=models.CharField(choices=[('GAL', 'Galvanized'), ('BLK', 'Blackened')], max_length=10, verbose_name='Cable Finishes'),
        ),
    ]
