# Generated by Django 5.2.10 on 2026-02-20 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_rename_order_id_taildownorder_orderid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taildownorder',
            old_name='Name',
            new_name='orderName',
        ),
    ]
