# Generated by Django 5.2.10 on 2026-02-24 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_rename_name_taildownorder_ordername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taildownorder',
            old_name='quntity',
            new_name='quantity',
        ),
    ]
