# Generated by Django 5.2.10 on 2026-02-25 12:24

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_jobdetails_showname'),
        ('customer', '0006_rename_quntity_taildownorder_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TailDownCart',
            fields=[
                ('orderId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orderName', models.CharField(default='TailDown No 1', max_length=255)),
                ('cableFinishes', models.CharField(choices=[('GAL', 'Galvanized'), ('BLK', 'Blackened')], max_length=10, verbose_name='Cable Finishes')),
                ('cableSize', models.CharField(max_length=10, verbose_name='Cable Size')),
                ('topType', models.CharField(max_length=10, verbose_name='Top Type')),
                ('endType', models.CharField(max_length=10, verbose_name='End Type')),
                ('turnbuckle', models.BooleanField(default=False, verbose_name='Turnbuckle')),
                ('chain', models.BooleanField(default=False, verbose_name='Chain')),
                ('tcOrder', models.CharField(max_length=10, verbose_name='Turnbuckle & Chain Order')),
                ('turnbuckleSize', models.CharField(max_length=10, verbose_name='Turnbuckle &Size')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)])),
                ('isOrdered', models.BooleanField(default=False, verbose_name='Cart Order')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('showName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.jobdetails', verbose_name='ShowName')),
            ],
        ),
    ]
