# Generated by Django 5.2.10 on 2026-03-18 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_taildownorder_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taildownorder',
            options={'permissions': [('view_all_taildownorders', 'Can view all customer orders')]},
        ),
    ]
