# Generated by Django 5.2.10 on 2026-03-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_alter_taildownorder_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='taildowncart',
            name='deliverBy',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taildownorder',
            name='deliverBy',
            field=models.DateField(blank=True, null=True),
        ),
    ]
