# Generated by Django 5.2.10 on 2026-03-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_taildowncart_deliverby_taildownorder_deliverby'),
    ]

    operations = [
        migrations.AddField(
            model_name='taildowncart',
            name='cableLength',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='taildowncart',
            name='cableLengthUnit',
            field=models.CharField(choices=[('ft', 'Feet'), ('in', 'Inches')], default='ft', max_length=2),
        ),
        migrations.AddField(
            model_name='taildownorder',
            name='cableLength',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='taildownorder',
            name='cableLengthUnit',
            field=models.CharField(choices=[('ft', 'Feet'), ('in', 'Inches')], default='ft', max_length=2),
        ),
    ]
