# Generated by Django 5.2.10 on 2026-03-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_taildowncart_cablelength_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taildowncart',
            name='chainLength',
            field=models.CharField(default='3f', max_length=10),
        ),
        migrations.AddField(
            model_name='taildownorder',
            name='chainLength',
            field=models.CharField(default='3ft', max_length=10),
        ),
        migrations.AlterField(
            model_name='taildownorder',
            name='cableLength',
            field=models.DecimalField(decimal_places=2, default='3', max_digits=10),
        ),
    ]
