# Generated by Django 5.2.10 on 2026-03-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_taildowncart_chainlength_taildownorder_chainlength_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taildowncart',
            name='cableLength',
        ),
        migrations.RemoveField(
            model_name='taildowncart',
            name='cableLengthUnit',
        ),
        migrations.RemoveField(
            model_name='taildownorder',
            name='cableLength',
        ),
        migrations.RemoveField(
            model_name='taildownorder',
            name='cableLengthUnit',
        ),
        migrations.AddField(
            model_name='taildowncart',
            name='cableLengthFt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taildowncart',
            name='cableLengthIn',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taildownorder',
            name='cableLengthFt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taildownorder',
            name='cableLengthIn',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
