# Generated by Django 5.2.10 on 2026-03-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_remove_taildowncart_cablelength_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taildowncart',
            name='chainLength',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='taildownorder',
            name='chainLength',
            field=models.CharField(max_length=10),
        ),
    ]
