# Generated by Django 5.2.10 on 2026-03-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_alter_taildowncart_chainlength_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taildowncart',
            name='chainLength',
            field=models.CharField(blank=' ', max_length=10),
        ),
        migrations.AlterField(
            model_name='taildownorder',
            name='chainLength',
            field=models.CharField(blank=' ', max_length=10),
        ),
    ]
